// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaHJnrisb4jVYiRUctOnYTzG4tu3zhFX0',
    appId: '1:84069327102:web:a1dbf904930fd921d885af',
    messagingSenderId: '84069327102',
    projectId: 'app-filmes-2a0a7',
    authDomain: 'app-filmes-2a0a7.firebaseapp.com',
    storageBucket: 'app-filmes-2a0a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLMh1sORk-RzKx49yvJaJG-vbxvQ4x_pk',
    appId: '1:84069327102:android:c4f7af9151ccbb7bd885af',
    messagingSenderId: '84069327102',
    projectId: 'app-filmes-2a0a7',
    storageBucket: 'app-filmes-2a0a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArLt25Z80QpDxN2QZoBNTVUXKGwDnlAWQ',
    appId: '1:84069327102:ios:a79b1dee80db2bc3d885af',
    messagingSenderId: '84069327102',
    projectId: 'app-filmes-2a0a7',
    storageBucket: 'app-filmes-2a0a7.appspot.com',
    iosBundleId: 'br.com.academiadoflutter.appFilmes',
  );
}
